// flow-typed signature: 50dd067e452b5641d926b6c09939ffb4
// flow-typed version: <<STUB>>/babel-istanbul-loader_v0.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-istanbul-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-istanbul-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-istanbul-loader/index' {
  declare module.exports: $Exports<'babel-istanbul-loader'>;
}
declare module 'babel-istanbul-loader/index.js' {
  declare module.exports: $Exports<'babel-istanbul-loader'>;
}
