// flow-typed signature: 08f87274ec0560f667e2f5d0df6df02b
// flow-typed version: <<STUB>>/eslint-config-vue_v^2.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-vue/index' {
  declare module.exports: $Exports<'eslint-config-vue'>;
}
declare module 'eslint-config-vue/index.js' {
  declare module.exports: $Exports<'eslint-config-vue'>;
}
